### ISSUE TITLE
Add Drive page

### ISSUE THREAD

**Issue by icidasset** [fission-suite/fission-guide#11]
The "help" link in the Fission Drive app links to the Fission Guide (specifically the `/drive` page).

**Comment by bmann** [comment]
@icidasset now that I think about it, we should have a link to the guide, but also a link to support.

We really really want to hear from people :) I _think_ "Help" Or "Need Help? Visit Support" should lead to support, where a ? or Guide or Docs leads to the Guide?

**Comment by bmann** [comment]
I created an initial version, made a new "Group" that starts at https://guide.fission.codes/drive and made an initial preview page. Should document / screenshot all features here.
