### ISSUE TITLE
Missing Dependencies in Installation Guide

### ISSUE THREAD

**Issue by fubuloubu** [fission-suite/fission-guide#19]
# Summary
https://guide.fission.codes/installation and https://guide.fission.codes/getting-started are both currently 404 under https://github.com/fission-suite/fission#binary-releases

## Problem
Some shared libraries are required:
```
libpq.so.5
libtinfo.so.5
```

### Impact
Can't use the CLI

## Solution

Better installation docs for Linux/Ubuntu

**Comment by bmann** [comment]
Thanks @fubuloubu -- I made these edits and we updated the README links too https://guide.fission.codes/hosting/installation
